maai: arreglar el models
Traceback (most recent call last):
  File "/home/clown/2-semester/3year2sem/vision/p1/main.py", line 161,
in <module>
    classifier = ShipClassifier(pretrained=args.pretrained,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clown/2-semester/3year2sem/vision/p1/ship_classifier.py",
line 25, in init
    self.create_model(pretrained, docked)
  File "/home/clown/2-semester/3year2sem/vision/p1/ship_classifier.py",
line 336, in create_model
    raise ValueError(f"Architecture {self.arquitecture} not supported")
ValueError: Architecture vgg_19 not supported
Traceback (most recent call last):
  File "/home/clown/2-semester/3year2sem/vision/p1/main.py", line 161,
in <module>
    classifier = ShipClassifier(pretrained=args.pretrained,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clown/2-semester/3year2sem/vision/p1/ship_classifier.py",
line 25, in init
    self.create_model(pretrained, docked)
  File "/home/clown/2-semester/3year2sem/vision/p1/ship_classifier.py",
line 347, in create_model
    self.model = self.update_classifier(model, n_outputs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/clown/2-semester/3year2sem/vision/p1/ship_classifier.py",
line 811, in update_classifier
    in_features = model.classifier[1].in_features
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/home/clown/2-semester/3year2sem/vision/vision_env/lib/python3.11/site-packages/torch/nn/modules/module.py",
line 1931, in getattr
    raise AttributeError(
AttributeError: 'Flatten' object has no attribute 'in_features'
/home/clown/2-semester/3year2sem/vision/vision_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:62:
UserWarning: The verbose parameter is deprecated. Please use
get_last_lr() to access the learning rate.